// Tareas precargadas del tablero (idénticas a las revisadas en el HTML original).
const ok = (arr) => arr.map((text) => ({ text, done: true }));
const pend = (arr) => arr.map((text) => ({ text, done: false }));

export const SEED = [
  // ───────────── Épica A · Panel maestro (super-admin) ─────────────
  { code: "A1", ep: "A", prio: "alta", status: "done",
    title: "Autenticación y roles de super-admin",
    description: "Login por email/contraseña con Supabase Auth; el rol de super-admin se decide por lista de correos.",
    subtasks: ok(["Login con email y contraseña (Supabase Auth)", "Detectar super-admin por SUPER_ADMIN_EMAILS", "Proteger /admin con requireSuperAdmin", "Cerrar sesión"]) },
  { code: "A2", ep: "A", prio: "alta", status: "done",
    title: "Crear, activar y suspender barberías",
    description: "Alta, edición y baja de barberías (tenants) desde el panel maestro.",
    subtasks: ok(["Crear barbería con slug y datos básicos", "Activar / desactivar (is_active)", "Editar datos de la barbería", "Eliminar barbería (borrado en cascada)"]) },
  { code: "A3", ep: "A", prio: "alta", status: "done",
    title: "Gestión de dueños y accesos por barbería",
    description: "Vincular cuentas dueñas a cada barbería y revocar su acceso (tabla tenant_users).",
    subtasks: ok(["Invitar dueño por email (crea el usuario si no existe)", "Definir o restablecer su contraseña", "Listar dueños de la barbería", "Revocar acceso de un dueño"]) },
  { code: "A4", ep: "A", prio: "media", status: "done",
    title: "Personalización de marca por barbería",
    description: "Identidad visual de cada barbería para su web pública.",
    subtasks: ok(["Subir logo", "Elegir color de acento", "Foto de portada del local", "Restringir logo y Maps al super-admin"]) },
  { code: "A5", ep: "A", prio: "media", status: "done",
    title: "Configuración avanzada de la barbería",
    description: 'Ajustes técnicos por barbería desde "Configuración avanzada".',
    subtasks: ok(["Slug / subdominio", "Zona horaria", "Duración del slot (slot_minutes)", "Enlace de Google Maps y WhatsApp"]) },
  { code: "A6", ep: "A", prio: "media", status: "todo",
    title: "Planes y límites de uso",
    description: "Definir planes con límites (citas/mes, staff, servicios) y aplicarlos por barbería.",
    subtasks: pend(["Modelar planes y sus límites", "Asignar un plan a cada barbería", "Bloquear acciones al superar el límite", "Avisar al acercarse al límite"]) },
  { code: "A7", ep: "A", prio: "alta", status: "todo",
    title: "Facturación y suscripciones recurrentes",
    description: "Cobro recurrente de la suscripción del SaaS a cada barbería.",
    subtasks: pend(["Integrar pasarela de suscripción (Stripe u otra)", "Estados: activa, en mora, cancelada", "Suspender barbería por impago", "Historial de facturas descargables"]) },
  { code: "A8", ep: "A", prio: "media", status: "todo",
    title: "Dashboard de métricas globales del SaaS",
    description: "Visión agregada del negocio para el operador del SaaS.",
    subtasks: pend(["Barberías activas / inactivas", "Citas e ingresos agregados", "Altas y bajas en el tiempo", "Ranking de barberías más activas"]) },
  { code: "A9", ep: "A", prio: "baja", status: "todo",
    title: "Centro de ayuda y soporte",
    description: "Canal de soporte y documentación para las barberías.",
    subtasks: pend(["Centro de ayuda / FAQ", "Bandeja de tickets o contacto", "Guías de primeros pasos"]) },

  // ───────────── Épica B · Panel del cliente (dueño) ─────────────
  { code: "B1", ep: "B", prio: "media", status: "todo",
    title: "Onboarding guiado al crear la barbería",
    description: "Asistente que guía al dueño en la puesta en marcha inicial.",
    subtasks: pend(["Checklist de configuración inicial", "Pasos: servicios → equipo → horario", "Indicador de avance del onboarding", "Atajo para compartir el enlace de reservas"]) },
  { code: "B2", ep: "B", prio: "alta", status: "done",
    title: "Configurar horario semanal y cierres de día",
    description: "Horario por día de la semana y cierre temporal de días sin perder las franjas.",
    subtasks: ok(["Franjas por día (working_hours)", "Varias franjas por día (pausa/almuerzo)", "Cerrar y reabrir un día (closed_weekdays)", "Rechazar reservas en día cerrado (validación en servidor)"]) },
  { code: "B3", ep: "B", prio: "media", status: "todo",
    title: "Feriados y cierres por fecha concreta",
    description: "Cerrar fechas específicas (feriados, vacaciones), no solo días de la semana.",
    subtasks: pend(["Cerrar una fecha puntual", "Rango de fechas (vacaciones)", "Excluir esas fechas de la disponibilidad"]) },
  { code: "B4", ep: "B", prio: "alta", status: "done",
    title: "Gestionar servicios (nombre, duración, precio)",
    description: "Catálogo de servicios de la barbería.",
    subtasks: ok(["Crear / editar servicio", "Duración en minutos", "Precio (price_cents) con formato de moneda", "Activar / desactivar servicio"]) },
  { code: "B5", ep: "B", prio: "alta", status: "done",
    title: "Gestionar equipo / barberos",
    description: "Alta y gestión del equipo; la capacidad de la agenda depende de los barberos activos.",
    subtasks: ok(["Crear / editar barbero", "Foto del barbero", "Activar / desactivar", "Capacidad = nº de barberos activos"]) },
  { code: "B6", ep: "B", prio: "media", status: "todo",
    title: "Roles y permisos del equipo",
    description: "Distinguir barbero de administrador y dar login propio a cada miembro.",
    subtasks: pend(["Rol barbero vs. administrador", "Login propio por barbero", "Restringir vistas según rol", "Que cada barbero vea solo su agenda"]) },
  { code: "B7", ep: "B", prio: "alta", status: "done",
    title: "Agenda de citas (vista por día)",
    description: "Agenda diaria del panel con los indicadores del día.",
    subtasks: ok(["Listar citas del día en la zona horaria del negocio", "Ver servicio, barbero y cliente", "KPIs del día (hoy, pendientes, clientes, ingresos)", "Navegar entre días"]) },
  { code: "B8", ep: "B", prio: "media", status: "todo",
    title: "Vistas de calendario semana y mes",
    description: "Ampliar la agenda con vistas de semana y mes (hoy solo hay vista por día).",
    subtasks: pend(["Vista semanal", "Vista mensual", "Navegación entre periodos", "Filtrar por barbero"]) },
  { code: "B9", ep: "B", prio: "alta", status: "done",
    title: "Crear y gestionar citas desde el panel",
    description: "Citas manuales del dueño (incluye histórico) y cancelación.",
    subtasks: ok(["Crear cita manual (diálogo de nueva cita)", "Permitir citas en el pasado (histórico)", "Cancelar cita", "Evitar doble reserva con índice único"]) },
  { code: "B10", ep: "B", prio: "media", status: "progress",
    title: "Ficha de cliente con historial y notas",
    description: "Clientes derivados de las citas; falta enriquecer con notas y contacto.",
    subtasks: [
      { text: "Listado de clientes agrupados por teléfono", done: true },
      { text: "Conteo de visitas y última visita", done: true },
      { text: "Buscar por nombre o teléfono", done: true },
      { text: "Notas internas por cliente", done: false },
      { text: "Datos de contacto y email del cliente", done: false }] },
  { code: "B11", ep: "B", prio: "alta", status: "todo",
    title: "Notificaciones automáticas (email / SMS / WhatsApp)",
    description: "Avisos automáticos al reservar; hoy se promete en el landing pero no está implementado.",
    subtasks: pend(["Confirmación de reserva al cliente", "Aviso de nueva cita al negocio", "Plantillas de mensaje configurables", "Elegir canales activos por barbería"]) },
  { code: "B12", ep: "B", prio: "alta", status: "todo",
    title: "Recordatorios y control de ausencias (no-show)",
    description: "Reducir ausencias con recordatorios y seguimiento de no-show.",
    subtasks: pend(["Recordatorio previo a la cita", "Marcar cita como no-show", "Política de ausencias", "Estadística de ausencias"]) },
  { code: "B13", ep: "B", prio: "media", status: "done",
    title: "Personalizar página pública de reservas",
    description: "La web pública de cada barbería usa su propia marca.",
    subtasks: ok(["Aplicar color de acento y logo", "Foto de portada", "Botón de WhatsApp y mapa", "Descripción y datos de contacto"]) },
  { code: "B14", ep: "B", prio: "media", status: "todo",
    title: "Pagos en línea y depósitos al reservar",
    description: "Cobro o depósito al reservar como protección anti no-show (estilo Fresha).",
    subtasks: pend(["Integrar pasarela de pago", "Depósito o pago total del servicio", "Política de reembolso", "Conciliar el pago con la cita"]) },
  { code: "B15", ep: "B", prio: "media", status: "progress",
    title: "Reportes: citas, ingresos y clientes",
    description: "KPIs básicos ya calculados; faltan reportes desglosados y exportación.",
    subtasks: [
      { text: "Citas de hoy y pendientes", done: true },
      { text: "Ingresos del mes", done: true },
      { text: "Total de clientes únicos", done: true },
      { text: "Reporte por barbero / servicio", done: false },
      { text: "Exportar a CSV", done: false }] },

  // ───────────── Épica C · Usuario final ─────────────
  { code: "C1", ep: "C", prio: "alta", status: "done",
    title: "Ver disponibilidad en tiempo real",
    description: "Huecos calculados al instante según horario, duración y barberos.",
    subtasks: ok(["Calcular huecos por horario y duración", "Capacidad según nº de barberos", "Marcar huecos ocupados (tachados)", "Omitir huecos en el pasado"]) },
  { code: "C2", ep: "C", prio: "alta", status: "done",
    title: "Flujo de reserva paso a paso",
    description: "Servicio → barbero → fecha → hora → datos → confirmar, optimizado para móvil.",
    subtasks: ok(["Elegir servicio", 'Elegir barbero o "cualquiera"', "Elegir fecha y hora", "Ingresar datos y confirmar (POST /api/appointments)"]) },
  { code: "C3", ep: "C", prio: "baja", status: "done",
    title: "Recordar datos del cliente",
    description: "Autocompletar al cliente recurrente en su mismo dispositivo.",
    subtasks: ok(["Guardar nombre y teléfono en el dispositivo", "Rellenar automáticamente en la próxima reserva"]) },
  { code: "C4", ep: "C", prio: "alta", status: "done",
    title: "Confirmación de la cita",
    description: "Confirmación inmediata tras reservar, con validación en servidor.",
    subtasks: ok(["Crear la cita en estado confirmado", "Mostrar resumen de la reserva", "Validar en servidor (hora pasada, solapes, día cerrado)"]) },
  { code: "C5", ep: "C", prio: "alta", status: "todo",
    title: "Recordatorio automático antes de la cita",
    description: "Aviso al cliente antes de su cita (depende de notificaciones y cola).",
    subtasks: pend(["Programar recordatorio (ej. 24 h y 2 h antes)", "Enviar por el canal elegido", "Enlazar con la cola de notificaciones"]) },
  { code: "C6", ep: "C", prio: "media", status: "todo",
    title: "Cancelar / reagendar por el cliente",
    description: "Que el propio cliente gestione su cita según la política del negocio (hoy solo cancela el dueño).",
    subtasks: pend(["Enlace de gestión de la cita", "Cancelar dentro del plazo permitido", "Reagendar a otro hueco libre", "Avisar al negocio del cambio"]) },
  { code: "C7", ep: "C", prio: "baja", status: "todo",
    title: "Historial de citas del cliente",
    description: "Que el cliente vea sus citas pasadas y futuras.",
    subtasks: pend(["Listar citas pasadas y futuras", "Reservar de nuevo en un clic"]) },
  { code: "C8", ep: "C", prio: "baja", status: "todo",
    title: "Reseñas y valoraciones tras la cita",
    description: "Pedir valoración al terminar y mostrarla en la web pública (estilo Fresha).",
    subtasks: pend(["Solicitar valoración tras completar la cita", "Puntuación y comentario", "Mostrar valoraciones en la web pública"]) },
  { code: "C9", ep: "C", prio: "baja", status: "todo",
    title: "Lista de espera para horarios llenos",
    description: "Apuntarse a un horario sin hueco y avisar si se libera (estilo Fresha).",
    subtasks: pend(["Apuntarse cuando no hay hueco", "Avisar si se libera el horario"]) },

  // ───────────── Épica D · Infraestructura ─────────────
  { code: "D1", ep: "D", prio: "alta", status: "done",
    title: "Arquitectura multi-tenant",
    description: "Datos aislados por barbería mediante tenant_id.",
    subtasks: ok(["tenant_id en todas las tablas", "Filtrado por barbería en cada consulta", "Borrado en cascada por barbería"]) },
  { code: "D2", ep: "D", prio: "media", status: "done",
    title: "Enrutado por subdominio",
    description: "Cada barbería se sirve en su subdominio (barberia.navaja.cr).",
    subtasks: ok(["Detectar subdominio del Host (proxy.ts)", "Reescribir a /s/[slug]", "Excluir API y estáticos del matcher"]) },
  { code: "D3", ep: "D", prio: "baja", status: "todo",
    title: "Dominios personalizados propios",
    description: "Permitir que una barbería use su propio dominio.",
    subtasks: pend(["Mapear dominio externo a la barbería", "Verificación de dominio", "Certificados / SSL automáticos"]) },
  { code: "D4", ep: "D", prio: "alta", status: "done",
    title: "Seguridad: RLS y autorización por barbería",
    description: "Aislamiento real de datos: RLS + guardas en el servidor.",
    subtasks: ok(["RLS activada en todas las tablas", "Lectura pública solo de filas activas", "appointments sin acceso público (solo service role)", "requireTenantAccess en acciones y rutas"]) },
  { code: "D5", ep: "D", prio: "alta", status: "done",
    title: "Prevención de doble reserva",
    description: "Evitar choques de reservas ante concurrencia.",
    subtasks: ok(["Índice único (staff_id, starts_at) en confirmadas", "Manejar el conflicto 23505 con mensaje claro", "Revalidar solapes en el servidor"]) },
  { code: "D6", ep: "D", prio: "alta", status: "done",
    title: "Zonas horarias y DST correctos",
    description: "Toda la lógica de horas respeta la zona horaria del negocio.",
    subtasks: ok(["Conversión hora local ↔ UTC (zonedWallToUtc)", "Día de la semana en la TZ del negocio", "Guardar siempre en UTC (timestamptz)"]) },
  { code: "D7", ep: "D", prio: "media", status: "todo",
    title: "Cola de envío de notificaciones",
    description: "Infraestructura de envío fiable para los avisos.",
    subtasks: pend(["Encolar los mensajes a enviar", "Reintentos ante fallo", "Registro de entregas"]) },
  { code: "D8", ep: "D", prio: "baja", status: "todo",
    title: "Integraciones externas",
    description: "Conectar con servicios de terceros (calendario y pagos).",
    subtasks: pend(["Sincronizar con Google Calendar", "Webhook de la pasarela de pago", "Claves / API por barbería"]) },
  { code: "D9", ep: "D", prio: "baja", status: "review",
    title: "Migraciones y respaldos de base de datos",
    description: "Migraciones versionadas listas; faltan respaldos automáticos verificados.",
    subtasks: [
      { text: "Migraciones versionadas (supabase/migrations)", done: true },
      { text: "Script para aplicarlas (run-sql.mjs)", done: true },
      { text: "Respaldos automáticos", done: false },
      { text: "Restauración probada", done: false }] },
];
